"""Configuration and constants for the AI music detector."""

import os

# ---------------------------------------------------------------------------
# Server
# ---------------------------------------------------------------------------
HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", "8000"))
UPLOAD_DIR = os.getenv("UPLOAD_DIR", "/tmp/ai_music_uploads")
MAX_FILE_BYTES = int(os.getenv("MAX_FILE_BYTES", str(100 * 1024 * 1024)))  # 100 MB

# ---------------------------------------------------------------------------
# Recognition / search
# ---------------------------------------------------------------------------
SHAZAM_TIMEOUT = int(os.getenv("SHAZAM_TIMEOUT", "45"))
YOUTUBE_SEARCH_TIMEOUT = int(os.getenv("YOUTUBE_SEARCH_TIMEOUT", "20"))
YOUTUBE_MAX_RESULTS = int(os.getenv("YOUTUBE_MAX_RESULTS", "5"))

# ---------------------------------------------------------------------------
# Acoustic analysis
# ---------------------------------------------------------------------------
ANALYSIS_SEGMENT_SECONDS = int(os.getenv("ANALYSIS_SEGMENT_SECONDS", "60"))
ANALYSIS_HOP_SECONDS = int(os.getenv("ANALYSIS_HOP_SECONDS", "30"))
TARGET_SAMPLE_RATE = int(os.getenv("TARGET_SAMPLE_RATE", "22050"))
N_MFCC = int(os.getenv("N_MFCC", "13"))
N_FFT = int(os.getenv("N_FFT", "2048"))
HOP_LENGTH = int(os.getenv("HOP_LENGTH", "512"))

# ---------------------------------------------------------------------------
# Decision / fuzzy thresholds
# ---------------------------------------------------------------------------
HUMAN_THRESHOLD = float(os.getenv("HUMAN_THRESHOLD", "35.0"))
AI_THRESHOLD = float(os.getenv("AI_THRESHOLD", "65.0"))

# ---------------------------------------------------------------------------
# Known AI music generation tool signatures (tags, encoders, comments, etc.)
# ---------------------------------------------------------------------------
AI_TOOL_SIGNATURES = {
    "suno": {"names": ["suno"], "label": "Suno", "score": 85},
    "sondo": {"names": ["sondo"], "label": "Sondo", "score": 80},
    "gemini": {"names": ["gemini"], "label": "Gemini", "score": 75},
    "mureka": {"names": ["mureka"], "label": "Mureka", "score": 80},
    "aiva": {"names": ["aiva"], "label": "AIVA", "score": 80},
    "mubert": {"names": ["mubert"], "label": "Mubert", "score": 80},
    "soundful": {"names": ["soundful"], "label": "Soundful", "score": 80},
    "soundraw": {"names": ["soundraw"], "label": "Soundraw", "score": 80},
    "landr": {"names": ["landr"], "label": "Landr", "score": 70},
    "beatoven": {"names": ["beatoven"], "label": "Beatoven", "score": 80},
    "moises": {"names": ["moises"], "label": "Moises", "score": 75},
    "udio": {"names": ["udio"], "label": "Udio", "score": 85},
    "musicgpt": {"names": ["musicgpt", "music gpt"], "label": "MusicGPT", "score": 80},
    "elevenlabs_music": {"names": ["elevenlabs music", "elevenlabs"], "label": "ElevenLabs Music", "score": 85},
    "musiccreator": {"names": ["musiccreator ai", "musiccreator"], "label": "MusicCreator AI", "score": 80},
    "aisong": {"names": ["aisong", "ai song"], "label": "AISong", "score": 80},
    "vidnoz": {"names": ["vidnoz ai generador", "vidnoz ai", "vidnoz"], "label": "Vidnoz AI", "score": 80},
    "music_muse": {"names": ["music muse"], "label": "Music Muse", "score": 80},
    "songdo": {"names": ["song.do", "songdo"], "label": "Song.do", "score": 80},
    "loudly": {"names": ["loudly"], "label": "Loudly", "score": 80},
    "musicfui": {"names": ["musicfui"], "label": "Musicfui", "score": 80},
    "aimusicgen": {"names": ["aimusicgen", "ai music gen"], "label": "AIMusicGen", "score": 80},
    "amper": {"names": ["amper music", "amper"], "label": "Amper Music", "score": 80},
    "canva": {"names": ["canva"], "label": "Canva", "score": 70},
    "aimakesong": {"names": ["aimakesong", "ai makesong"], "label": "AiMakesong", "score": 80},
    "lyria": {"names": ["lyria"], "label": "Lyria", "score": 80},
    "adobe": {"names": ["adobe"], "label": "Adobe", "score": 70},
    "treblo": {"names": ["treblo"], "label": "Treblo", "score": 80},
}

GENERIC_AI_HINTS = [
    "ai generated", "ai-generated", "generated by ai", "made with ai",
    "artificial intelligence", "machine generated", "suno ai", "udio ai",
    "text to music", "text-to-music", "prompt generated",
]

# ---------------------------------------------------------------------------
# Cover / official video detection
# ---------------------------------------------------------------------------
OFFICIAL_VIDEO_KEYWORDS = [
    "official video", "official music video", "video oficial",
    "vevo", "official audio", "audio oficial",
]
COVER_KEYWORDS = [
    "cover", "karaoke", "instrumental", "remix", "tributo", "version",
    "versión", "reinterpretación", "reinterpretacion",
]
