"""FastAPI REST API for AI-generated music detection."""

import os
import shutil
import uuid
from contextlib import asynccontextmanager
from typing import Optional

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.analyzer import analyze_audio
from app.config import MAX_FILE_BYTES, UPLOAD_DIR
from app.models import AnalysisResponse, HealthResponse


@asynccontextmanager
async def lifespan(app: FastAPI):
    os.makedirs(UPLOAD_DIR, exist_ok=True)
    yield
    # Optional cleanup on shutdown could go here


app = FastAPI(
    title="AI Music Detector API",
    description=(
        "Detects whether an audio file was likely generated by AI. "
        "Combines metadata inspection, Shazam recognition, YouTube official video lookup, "
        "acoustic feature extraction (librosa/pyAudioAnalysis), and lyric heuristics."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


ALLOWED_EXTENSIONS = {".mp3", ".wav", ".flac", ".ogg", ".m4a", ".aac", ".wma", ".opus"}


def _validate_file(file: UploadFile) -> None:
    if not file.filename:
        raise HTTPException(status_code=400, detail="Missing file name.")
    ext = os.path.splitext(file.filename)[1].lower()
    if ext not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file extension '{ext}'. Allowed: {', '.join(ALLOWED_EXTENSIONS)}",
        )


def _save_upload(file: UploadFile) -> str:
    upload_id = uuid.uuid4().hex
    ext = os.path.splitext(file.filename or "audio.mp3")[1].lower()
    destination = os.path.join(UPLOAD_DIR, f"{upload_id}{ext}")
    with open(destination, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
    return destination


@app.get("/", response_model=HealthResponse)
async def root():
    return HealthResponse(status="ok", service="ai-music-detector")


@app.get("/api/health", response_model=HealthResponse)
async def health():
    return HealthResponse(status="ok", service="ai-music-detector")


@app.post("/api/analyze", response_model=AnalysisResponse)
async def analyze(
    audio: UploadFile = File(..., description="Audio file to analyze"),
    lyrics: Optional[str] = Form(None, description="Optional lyrics text for analysis"),
):
    """Upload an audio file and receive a JSON AI-likelihood report."""
    _validate_file(audio)

    temp_path = _save_upload(audio)
    try:
        size = os.path.getsize(temp_path)
        if size > MAX_FILE_BYTES:
            raise HTTPException(
                status_code=413,
                detail=f"File too large ({size} bytes). Max allowed: {MAX_FILE_BYTES} bytes.",
            )

        result = await analyze_audio(temp_path, provided_lyrics=lyrics)
        return JSONResponse(content=result)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Analysis failed: {e}")
    finally:
        try:
            os.remove(temp_path)
        except Exception:
            pass


if __name__ == "__main__":
    import uvicorn
    from app.config import HOST, PORT
    uvicorn.run("app.main:app", host=HOST, port=PORT, reload=True)
